/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SeniorCareRouteImport } from './routes/senior-care'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AlzheimersDementiaCareRouteImport } from './routes/alzheimers-dementia-care'
import { Route as AdultDayHealthCareRouteImport } from './routes/adult-day-health-care'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminDocumentsRouteImport } from './routes/admin.documents'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminContactsRouteImport } from './routes/admin.contacts'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAppointmentsRouteImport } from './routes/admin.appointments'
import { Route as AdminAiChatRouteImport } from './routes/admin.ai-chat'
import { Route as AdminAiRouteImport } from './routes/admin.ai'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SeniorCareRoute = SeniorCareRouteImport.update({
  id: '/senior-care',
  path: '/senior-care',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AlzheimersDementiaCareRoute = AlzheimersDementiaCareRouteImport.update({
  id: '/alzheimers-dementia-care',
  path: '/alzheimers-dementia-care',
  getParentRoute: () => rootRouteImport,
} as any)
const AdultDayHealthCareRoute = AdultDayHealthCareRouteImport.update({
  id: '/adult-day-health-care',
  path: '/adult-day-health-care',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDocumentsRoute = AdminDocumentsRouteImport.update({
  id: '/admin/documents',
  path: '/admin/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContactsRoute = AdminContactsRouteImport.update({
  id: '/admin/contacts',
  path: '/admin/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAppointmentsRoute = AdminAppointmentsRouteImport.update({
  id: '/admin/appointments',
  path: '/admin/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAiChatRoute = AdminAiChatRouteImport.update({
  id: '/admin/ai-chat',
  path: '/admin/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAiRoute = AdminAiRouteImport.update({
  id: '/admin/ai',
  path: '/admin/ai',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesRoute
  '/adult-day-health-care': typeof AdultDayHealthCareRoute
  '/alzheimers-dementia-care': typeof AlzheimersDementiaCareRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/senior-care': typeof SeniorCareRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/videos': typeof VideosRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/ai-chat': typeof AdminAiChatRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesRoute
  '/adult-day-health-care': typeof AdultDayHealthCareRoute
  '/alzheimers-dementia-care': typeof AlzheimersDementiaCareRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/senior-care': typeof SeniorCareRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/videos': typeof VideosRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/ai-chat': typeof AdminAiChatRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesRoute
  '/adult-day-health-care': typeof AdultDayHealthCareRoute
  '/alzheimers-dementia-care': typeof AlzheimersDementiaCareRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/senior-care': typeof SeniorCareRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/videos': typeof VideosRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/ai-chat': typeof AdminAiChatRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/activities'
    | '/adult-day-health-care'
    | '/alzheimers-dementia-care'
    | '/contact'
    | '/faq'
    | '/gallery'
    | '/senior-care'
    | '/services'
    | '/sitemap.xml'
    | '/testimonials'
    | '/videos'
    | '/admin/ai'
    | '/admin/ai-chat'
    | '/admin/appointments'
    | '/admin/audit'
    | '/admin/contacts'
    | '/admin/customers'
    | '/admin/documents'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/activities'
    | '/adult-day-health-care'
    | '/alzheimers-dementia-care'
    | '/contact'
    | '/faq'
    | '/gallery'
    | '/senior-care'
    | '/services'
    | '/sitemap.xml'
    | '/testimonials'
    | '/videos'
    | '/admin/ai'
    | '/admin/ai-chat'
    | '/admin/appointments'
    | '/admin/audit'
    | '/admin/contacts'
    | '/admin/customers'
    | '/admin/documents'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/settings'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/activities'
    | '/adult-day-health-care'
    | '/alzheimers-dementia-care'
    | '/contact'
    | '/faq'
    | '/gallery'
    | '/senior-care'
    | '/services'
    | '/sitemap.xml'
    | '/testimonials'
    | '/videos'
    | '/admin/ai'
    | '/admin/ai-chat'
    | '/admin/appointments'
    | '/admin/audit'
    | '/admin/contacts'
    | '/admin/customers'
    | '/admin/documents'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ActivitiesRoute: typeof ActivitiesRoute
  AdultDayHealthCareRoute: typeof AdultDayHealthCareRoute
  AlzheimersDementiaCareRoute: typeof AlzheimersDementiaCareRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  SeniorCareRoute: typeof SeniorCareRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TestimonialsRoute: typeof TestimonialsRoute
  VideosRoute: typeof VideosRoute
  AdminAiRoute: typeof AdminAiRoute
  AdminAiChatRoute: typeof AdminAiChatRoute
  AdminAppointmentsRoute: typeof AdminAppointmentsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminContactsRoute: typeof AdminContactsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDocumentsRoute: typeof AdminDocumentsRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/senior-care': {
      id: '/senior-care'
      path: '/senior-care'
      fullPath: '/senior-care'
      preLoaderRoute: typeof SeniorCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alzheimers-dementia-care': {
      id: '/alzheimers-dementia-care'
      path: '/alzheimers-dementia-care'
      fullPath: '/alzheimers-dementia-care'
      preLoaderRoute: typeof AlzheimersDementiaCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adult-day-health-care': {
      id: '/adult-day-health-care'
      path: '/adult-day-health-care'
      fullPath: '/adult-day-health-care'
      preLoaderRoute: typeof AdultDayHealthCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/documents': {
      id: '/admin/documents'
      path: '/admin/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contacts': {
      id: '/admin/contacts'
      path: '/admin/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AdminContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/appointments': {
      id: '/admin/appointments'
      path: '/admin/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AdminAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ai-chat': {
      id: '/admin/ai-chat'
      path: '/admin/ai-chat'
      fullPath: '/admin/ai-chat'
      preLoaderRoute: typeof AdminAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ai': {
      id: '/admin/ai'
      path: '/admin/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AdminAiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ActivitiesRoute: ActivitiesRoute,
  AdultDayHealthCareRoute: AdultDayHealthCareRoute,
  AlzheimersDementiaCareRoute: AlzheimersDementiaCareRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  SeniorCareRoute: SeniorCareRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TestimonialsRoute: TestimonialsRoute,
  VideosRoute: VideosRoute,
  AdminAiRoute: AdminAiRoute,
  AdminAiChatRoute: AdminAiChatRoute,
  AdminAppointmentsRoute: AdminAppointmentsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminContactsRoute: AdminContactsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDocumentsRoute: AdminDocumentsRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
