/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SeniorCareRouteImport } from './routes/senior-care'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as AlzheimersDementiaCareRouteImport } from './routes/alzheimers-dementia-care'
import { Route as AdultDayHealthCareRouteImport } from './routes/adult-day-health-care'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SeniorCareRoute = SeniorCareRouteImport.update({
  id: '/senior-care',
  path: '/senior-care',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const AlzheimersDementiaCareRoute = AlzheimersDementiaCareRouteImport.update({
  id: '/alzheimers-dementia-care',
  path: '/alzheimers-dementia-care',
  getParentRoute: () => rootRouteImport,
} as any)
const AdultDayHealthCareRoute = AdultDayHealthCareRouteImport.update({
  id: '/adult-day-health-care',
  path: '/adult-day-health-care',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesRoute
  '/adult-day-health-care': typeof AdultDayHealthCareRoute
  '/alzheimers-dementia-care': typeof AlzheimersDementiaCareRoute
  '/gallery': typeof GalleryRoute
  '/senior-care': typeof SeniorCareRoute
  '/services': typeof ServicesRoute
  '/testimonials': typeof TestimonialsRoute
  '/videos': typeof VideosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesRoute
  '/adult-day-health-care': typeof AdultDayHealthCareRoute
  '/alzheimers-dementia-care': typeof AlzheimersDementiaCareRoute
  '/gallery': typeof GalleryRoute
  '/senior-care': typeof SeniorCareRoute
  '/services': typeof ServicesRoute
  '/testimonials': typeof TestimonialsRoute
  '/videos': typeof VideosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesRoute
  '/adult-day-health-care': typeof AdultDayHealthCareRoute
  '/alzheimers-dementia-care': typeof AlzheimersDementiaCareRoute
  '/gallery': typeof GalleryRoute
  '/senior-care': typeof SeniorCareRoute
  '/services': typeof ServicesRoute
  '/testimonials': typeof TestimonialsRoute
  '/videos': typeof VideosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/activities'
    | '/adult-day-health-care'
    | '/alzheimers-dementia-care'
    | '/gallery'
    | '/senior-care'
    | '/services'
    | '/testimonials'
    | '/videos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/activities'
    | '/adult-day-health-care'
    | '/alzheimers-dementia-care'
    | '/gallery'
    | '/senior-care'
    | '/services'
    | '/testimonials'
    | '/videos'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/activities'
    | '/adult-day-health-care'
    | '/alzheimers-dementia-care'
    | '/gallery'
    | '/senior-care'
    | '/services'
    | '/testimonials'
    | '/videos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ActivitiesRoute: typeof ActivitiesRoute
  AdultDayHealthCareRoute: typeof AdultDayHealthCareRoute
  AlzheimersDementiaCareRoute: typeof AlzheimersDementiaCareRoute
  GalleryRoute: typeof GalleryRoute
  SeniorCareRoute: typeof SeniorCareRoute
  ServicesRoute: typeof ServicesRoute
  TestimonialsRoute: typeof TestimonialsRoute
  VideosRoute: typeof VideosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/senior-care': {
      id: '/senior-care'
      path: '/senior-care'
      fullPath: '/senior-care'
      preLoaderRoute: typeof SeniorCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alzheimers-dementia-care': {
      id: '/alzheimers-dementia-care'
      path: '/alzheimers-dementia-care'
      fullPath: '/alzheimers-dementia-care'
      preLoaderRoute: typeof AlzheimersDementiaCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adult-day-health-care': {
      id: '/adult-day-health-care'
      path: '/adult-day-health-care'
      fullPath: '/adult-day-health-care'
      preLoaderRoute: typeof AdultDayHealthCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ActivitiesRoute: ActivitiesRoute,
  AdultDayHealthCareRoute: AdultDayHealthCareRoute,
  AlzheimersDementiaCareRoute: AlzheimersDementiaCareRoute,
  GalleryRoute: GalleryRoute,
  SeniorCareRoute: SeniorCareRoute,
  ServicesRoute: ServicesRoute,
  TestimonialsRoute: TestimonialsRoute,
  VideosRoute: VideosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
